### ISSUE TITLE
looking at an energy anihilation plane instantly crashes.

### ISSUE THREAD

**Issue by supremedutchgamer** [AzazeII/Applied-Integrations#17]
**Describe the bug**
when looking at the energy annihilation plane, you'll immediately crash

**To Reproduce**
make an ME system, hook up an energy annihilation plane to it.

**Expected behavior**
no idea, i cant find any info anywhere on how the energy annihilation plane is supposed to work.

**Enviroment**
-applied integrations beta 8.0.14.1
-Applied energistics 2 RV6 stable 6
-forge 14.23.5.2838

**Additional context**
https://paste.dimdev.org/isemuwigum.mccrash

**Comment by indiscrete-void** [comment]
From your crashlog:
`-- PartEnergyImport being ticked. --
  CurrentTickRate: 2
  MinTickRate: 2
  MaxTickRate: 40
  MachineType: AppliedIntegrations.Parts.Energy.PartEnergyImport
  GridBlockType: appeng.me.helpers.AENetworkProxy
  ConnectedSides: [INTERNAL]
  Location: dimension=0, x=1073, y=4, z=-688`
So issue wasn't most likely caused by annihilation plane

**Comment by indiscrete-void** [comment]
Just reproduced issue, nothing happens when i look at annihilation plane, so it's definitely caused by energy import bus. Crash log 📄 is enough to fix it
![Screenshot 2019-06-26 at 13 43 43](https://user-images.githubusercontent.com/32298517/60174177-2a223500-9819-11e9-9e47-782966f44ac9.png)

**Comment by indiscrete-void** [comment]
Cannot reproduce. Issue may be caused by mod conflict, but i have no idea what mod can affect mechanics of network monitor in AE2
