### ISSUE TITLE
Rendering crash with abyssalcraft

### ISSUE THREAD

**Issue by ym1025** [AzazeII/Applied-Integrations#20]
**Describe the bug**
I right clicked on Applied Integration's Energy Interface,on GUI, I moved the cursor on the slot,Minecraft crashed.
And I re-joined the world, a little later,I had move server selection screen.

**To Reproduce**
1.right click on energy interface
2.cursor move under slot

**Expected behavior**
some texts will display

**Screenshots**

**Enviroment**
 - Mod version:8.0.16.1
 - Applied energistics 2 version:rv6-stable-7
 - Forge version:14.23.5.2847

**Additional context**
Crash report: https://pastebin.com/pYAyMDcC
log: https://pastebin.com/kC0sdh7H (Just a little bit towards the end)

This issue on Abyssalcraft's Github: https://github.com/Shinoow/AbyssalCraft/issues/403

**Comment by indiscrete-void** [comment]
As you can see from crashlog
`java.lang.NullPointerException
    at com.shinoow.abyssalcraft.client.handlers.AbyssalCraftClientEventHooks.tooltipFont(AbyssalCraftClientEventHooks.java:291)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1714_AbyssalCraftClientEventHooks_tooltipFont_Pre.invoke(.dynamic)`
This issue is related to custom tooltip handler from AbyssalCraft. I think you need to submit issue to AbyssalCraft GitHub

**Comment by Shinoow** [comment]
No, the issue is related to you inserting a null into a tooltip (which shouldn't have any null values).
https://github.com/AzazeII/Applied-Integrations/blob/1.12.2/src/main/java/AppliedIntegrations/Gui/Part/GuiEnergyInterface.java#L144
This line calls the following:
https://github.com/AzazeII/Applied-Integrations/blob/1.12.2/src/main/java/AppliedIntegrations/api/Storage/EnergyStack.java#L71-L77
Which can return null (and as the crash shows, does). Due to the fact that the tooltip list isn't empty, the code related to tooltip handling will continue to process, which then crashes on my end when a null value is presented to my event handler (as the nonnull list shouldn't contain any null values).
Null check the energy name before adding it to the tooltip!

**Comment by indiscrete-void** [comment]
Thanks for your response. Now i see this issue is related to my mod. I'll replace null in return with "NULL" to make sure this issue will not crash game and only show "NULL" in tooltip. Also i'll null check the energy name in all GUIs where energy slot widget is used

**Comment by indiscrete-void** [comment]
Also there is WidgetEnergySelector that also uses EnergyStack...

**Comment by indiscrete-void** [comment]
I'm not sure if this last commit really fixes the issue (don't have time to run it with abyssalcraft right know), but by logic it should fix this issue.

**Comment by Shinoow** [comment]
As long as it isn't actually a null value, it should work just fine.

**Comment by indiscrete-void** [comment]
If my computer will survive three running IDEs and minecraft i'll test it and upload new version if it fixes issue

**Comment by indiscrete-void** [comment]
https://www.curseforge.com/minecraft/mc-mods/applied-integrations/files/2842730
