### ISSUE TITLE
Energy Filter

### ISSUE THREAD

**Issue by auddie2015** [AzazeII/Applied-Integrations#24]
**Describe the bug**
RF goes in, Joules go out. Well, they don't go out. Nothing goes out. It won't fill machines, energy cells, batteries. All that gets filled are the storage disks. The termal shows RF energy stored but the export bus only exports J.

**To Reproduce**
Filter RF and it turns to J in an export bus. 

**Expected behavior**
The bus actually export RF.

**Screenshots**

**Enviroment**
 - Mod version 8.0.16.7
 - Applied energistics 2 version rv-6-stable-7
 - Forge version 1.12.2-14.23.5.2847

**Additional context**
No

I know this is a terse report but I don't know any other way to say it. RF in, nothing out.

**Comment by indiscrete-void** [comment]
Cannot reproduce. Everything is working fine in my test world. 
When i'm putting RF-energy container like energy cube from mekanism(it is resolved as RF storage in GUI, since it can also accept RF. If you want to filter joules you should put configurator or any other item storing J from mekanism) export bus properly filters RF and exports RF energy from network.
Also if you mean that export bus doesn't exports RF when Joules are stored, it's intended. There is no way for concerting energy from one system to another for now.
