### ISSUE TITLE
Crash while loading server

### ISSUE THREAD

**Issue by iamceph** [AzazeII/Applied-Integrations#3]
Hello, I added AI into my server, cannot start now. Keeps crashing as it is only clientside mod ⭕️

Crash: https://hastebin.com/emuvanevex.sql

**Comment by AzazeII** [comment]
From your crash log: 
>Minecraft Version: 1.12.2

In minecraft 1.12.2 packet system is sligthly changed, but currently i'm working only on render and JSON models, and packet system in 1.12.2 version of AI is imported from 1.7.10 version, and not changed at all, it will not work on any server, and i don't recommend to add Alpha AI to your server, because current alpha is unstable, and may cause a lot of crashes.
