### ISSUE TITLE
crash with YABBA

### ISSUE THREAD

**Issue by bick88** [AzazeII/Applied-Integrations#5]
I try to put your mod in too diffrent modpack and in each case, i have a carsh.

Same issue with Yabba : at com.latmod.yabba.client.YabbaClient.loadModelsAndSkins(YabbaClient.java:119)

https://pastebin.com/B9rDfNjh

**Comment by AzazeII** [comment]
I think it's some Yabba specific issue, because i'm not see any Applied integrations function call, or maybe it's yabba react on null texture of some template items, like p2p tunnels. Please wait for update where all models will be added

**Comment by bick88** [comment]
Ok thanks i put the issue on YAbba. I follow your mod from the begining and i would try on minecraft 1.12 because your mod looks awesome.

**Comment by AzazeII** [comment]
From https://github.com/LatvianModder/YABBA/issues/116:
> From what I can tell, some fluid's still icon is null, which should never happen. Blame other mod. Still, I patched it to ignore such fluids

If this issue is caused by null fluid's icons, than i think i can fix it. And yes, these fluids have no icons, because they was used as energy in 1.7.10 version, because AE Api in 1.7.10 didn't provided methods to create own storage channel. But now it can be fixed, wait for 8.0.7 update
